# Generated by Django 5.2.3 on 2025-06-24 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='image',
        ),
    ]
