# Generated by Django 5.2.3 on 2025-06-29 10:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_remove_client_image'),
        ('content', '0005_alter_document_options'),
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created_at'], 'verbose_name': 'مهمة', 'verbose_name_plural': 'المهام'},
        ),
        migrations.AddField(
            model_name='task',
            name='file_path',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='مسار الملف'),
        ),
        migrations.AddField(
            model_name='task',
            name='file_url',
            field=models.URLField(blank=True, max_length=1024, null=True, verbose_name='رابط الملف'),
        ),
        migrations.AlterField(
            model_name='task',
            name='assigned_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='الموظف المكلّف'),
        ),
        migrations.AlterField(
            model_name='task',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.client', verbose_name='العميل'),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, verbose_name='الوصف'),
        ),
        migrations.AlterField(
            model_name='task',
            name='documents',
            field=models.ManyToManyField(blank=True, to='content.document', verbose_name='مستندات إضافية'),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الاستحقاق'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد التنفيذ'), ('completed', 'منتهية'), ('overdue', 'متأخرة')], default='pending', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=255, verbose_name='عنوان المهمة'),
        ),
    ]
