# Generated by Django 5.2.15 on 2026-06-04 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_assigned_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='file_url',
        ),
    ]
