# Generated by Django 5.2.3 on 2025-06-29 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_remove_document_file_document_file_path_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={},
        ),
    ]
