# Generated by Django 5.2.3 on 2025-07-08 15:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_alter_document_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='allowed_users',
            field=models.ManyToManyField(blank=True, related_name='permitted_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='document',
            name='access_level',
            field=models.CharField(choices=[('public', 'عام'), ('private', 'خاص'), ('restricted', 'مقيّد'), ('admin_only', 'للمدراء فقط'), ('client_shared', 'مشترك مع عميل')], default='private', max_length=20),
        ),
    ]
