# Generated by Django 5.2.15 on 2026-06-04 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_document_allowed_users_alter_document_access_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='file_url',
        ),
    ]
